### ISSUE TITLE
There are several errors in the code

### ISSUE THREAD

**Issue by Icelame-31** [klightz/PSF#1]
Thank you for your sharing.
But there are several errors in the code.
Such as, the vizIter of train_flow.py(line 387), it may raise many errors.
The DATASET.pth is not found.(datasets/shapenet_data_pc.py line 139).
I hope you can revise those errors and check your code carefully as soon as possible.
Many thanks for you sharing your code again.

**Comment by klightz** [comment]
Hi! Thank you for your interest in our project.

I apologize for the confusion. Because I made numerous merges and did some cleaning before releasing the code to make it clearer, and I only tested the training part, some errors in the sampling part have occurred due to inconsistencies. I've already noted these errors on line 387. 

As for DATASET.pth, it's generated in sample_flow.py (Line 599). This corresponds to the sampling pair (x_0', x_1') in our paper's reflow section and is solely used in reflow and distill training. Therefore, after training a flow model, you can run sample_flow.py to generate the DATASET.pth.
